[package]
name = "iouring_vs_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
libc = "*"
tokio = { version = "1", features = ["full"] }
eyre = "0.6.12"
io-uring = { git = "https://github.com/bits0rcerer/io-uring.git", branch = "buf-ring" }
socket2 = "0.5.8"
